services:
  db:
    image: mysql:8.4.6
    container_name: myapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      TZ: Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 30
    
  api:
    build:
      context: ./app_api
    container_name: myapp-api
    environment:
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_HOST: db
      DB_NAME: myapp
      DB_PORT: "3306"
      TZ: Asia/Bangkok
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  web:
    build:
      context: ./react_app
    container_name: myapp-web
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      VITE_API_BASE: "http://localhost:8000"

volumes:
  dbdata:
